//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Password_Bank {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Password_Bank.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string btnAbout_Main {
            get {
                return ResourceManager.GetString("btnAbout_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAdd_Main {
            get {
                return ResourceManager.GetString("btnAdd_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete_Main {
            get {
                return ResourceManager.GetString("btnDelete_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete_Recycle {
            get {
                return ResourceManager.GetString("btnDelete_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string btnLogIn_ucLoginSign {
            get {
                return ResourceManager.GetString("btnLogIn_ucLoginSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        internal static string btnRecycle_Main {
            get {
                return ResourceManager.GetString("btnRecycle_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register and Log In.
        /// </summary>
        internal static string btnRegister_ucLoginLog {
            get {
                return ResourceManager.GetString("btnRegister_ucLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btnRegister_ucLoginSign_Next {
            get {
                return ResourceManager.GetString("btnRegister_ucLoginSign_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew and Log In.
        /// </summary>
        internal static string btnRegister_ucLoginSign_RenewLog {
            get {
                return ResourceManager.GetString("btnRegister_ucLoginSign_RenewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string btnRestore_Recycle {
            get {
                return ResourceManager.GetString("btnRestore_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch_Main {
            get {
                return ResourceManager.GetString("btnSearch_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string btnSettings_Main {
            get {
                return ResourceManager.GetString("btnSettings_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdate_Main {
            get {
                return ResourceManager.GetString("btnUpdate_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Login Info.
        /// </summary>
        internal static string btnUpdateLoginInfo_Settings {
            get {
                return ResourceManager.GetString("btnUpdateLoginInfo_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string Code_ExitQuest_Main {
            get {
                return ResourceManager.GetString("Code_ExitQuest_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT?.
        /// </summary>
        internal static string Code_ExitQuest_Title {
            get {
                return ResourceManager.GetString("Code_ExitQuest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data added successfully!.
        /// </summary>
        internal static string dbcodes_Add_Main {
            get {
                return ResourceManager.GetString("dbcodes_Add_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA ADDED.
        /// </summary>
        internal static string dbcodes_Add_Title {
            get {
                return ResourceManager.GetString("dbcodes_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such data already exists!.
        /// </summary>
        internal static string dbcodes_AlreadyExists_Main {
            get {
                return ResourceManager.GetString("dbcodes_AlreadyExists_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALREADY EXISTS.
        /// </summary>
        internal static string dbcodes_AlreadyExists_Title {
            get {
                return ResourceManager.GetString("dbcodes_AlreadyExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data deleted successfully!.
        /// </summary>
        internal static string dbcodes_Delete_Main {
            get {
                return ResourceManager.GetString("dbcodes_Delete_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA DELETED.
        /// </summary>
        internal static string dbcodes_Delete_Title {
            get {
                return ResourceManager.GetString("dbcodes_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error! Error Code: {0}.
        /// </summary>
        internal static string dbcodes_Error_Main {
            get {
                return ResourceManager.GetString("dbcodes_Error_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string dbcodes_Error_Title {
            get {
                return ResourceManager.GetString("dbcodes_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data permanent delete successfully!.
        /// </summary>
        internal static string dbcodes_Permdelete_Main {
            get {
                return ResourceManager.GetString("dbcodes_Permdelete_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA PERMANENT DELETE.
        /// </summary>
        internal static string dbcodes_Permdelete_Title {
            get {
                return ResourceManager.GetString("dbcodes_Permdelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data restored successfully!.
        /// </summary>
        internal static string dbcodes_Restore_Main {
            get {
                return ResourceManager.GetString("dbcodes_Restore_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA RESTORED.
        /// </summary>
        internal static string dbcodes_Restore_Title {
            get {
                return ResourceManager.GetString("dbcodes_Restore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully!.
        /// </summary>
        internal static string dbcodes_Update_Main {
            get {
                return ResourceManager.GetString("dbcodes_Update_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA UPDATED.
        /// </summary>
        internal static string dbcodes_Update_Title {
            get {
                return ResourceManager.GetString("dbcodes_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter data!.
        /// </summary>
        internal static string frmMainCode_NoInfo_Main {
            get {
                return ResourceManager.GetString("frmMainCode_NoInfo_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO INFO.
        /// </summary>
        internal static string frmMainCode_NoInfo_Title {
            get {
                return ResourceManager.GetString("frmMainCode_NoInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the word to searched!.
        /// </summary>
        internal static string frmMainCode_NoSearchWord_Main {
            get {
                return ResourceManager.GetString("frmMainCode_NoSearchWord_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO SEARCH WORD.
        /// </summary>
        internal static string frmMainCode_NoSearchWord_Title {
            get {
                return ResourceManager.GetString("frmMainCode_NoSearchWord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such data was found!.
        /// </summary>
        internal static string frmMainCode_NoSuchData_Main {
            get {
                return ResourceManager.GetString("frmMainCode_NoSuchData_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT FOUND.
        /// </summary>
        internal static string frmMainCode_NoSuchData_Title {
            get {
                return ResourceManager.GetString("frmMainCode_NoSuchData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanent delete?.
        /// </summary>
        internal static string frmRecycleCode_DeleteQuest_Main {
            get {
                return ResourceManager.GetString("frmRecycleCode_DeleteQuest_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMANENT DELETE.
        /// </summary>
        internal static string frmRecycleCode_DeleteQuest_Title {
            get {
                return ResourceManager.GetString("frmRecycleCode_DeleteQuest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string frmRecycleCode_Listing_Description {
            get {
                return ResourceManager.GetString("frmRecycleCode_Listing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string frmRecycleCode_Listing_EMail {
            get {
                return ResourceManager.GetString("frmRecycleCode_Listing_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string frmRecycleCode_Listing_ID {
            get {
                return ResourceManager.GetString("frmRecycleCode_Listing_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string frmRecycleCode_Listing_Password {
            get {
                return ResourceManager.GetString("frmRecycleCode_Listing_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore?.
        /// </summary>
        internal static string frmRecycleCode_RestoreQuest_Main {
            get {
                return ResourceManager.GetString("frmRecycleCode_RestoreQuest_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTORE.
        /// </summary>
        internal static string frmRecycleCode_RestoreQuest_Title {
            get {
                return ResourceManager.GetString("frmRecycleCode_RestoreQuest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the new information you entered?
        ///
        ///E-Mail: {0}
        ///Password: {1}.
        /// </summary>
        internal static string frmSettingeCode_UpdateRequest_Main {
            get {
                return ResourceManager.GetString("frmSettingeCode_UpdateRequest_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address and password!.
        /// </summary>
        internal static string frmSettingsCode_InvalidInfo_Main {
            get {
                return ResourceManager.GetString("frmSettingsCode_InvalidInfo_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID INFORMATION.
        /// </summary>
        internal static string frmSettingsCode_InvalidInfo_Title {
            get {
                return ResourceManager.GetString("frmSettingsCode_InvalidInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changing information!.
        /// </summary>
        internal static string frmSettingsCode_NotChangeInfo_Main {
            get {
                return ResourceManager.GetString("frmSettingsCode_NotChangeInfo_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT CHANGE.
        /// </summary>
        internal static string frmSettingsCode_NotChangeInfo_Title {
            get {
                return ResourceManager.GetString("frmSettingsCode_NotChangeInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE LOGIN INFO.
        /// </summary>
        internal static string frmSettingsCode_UpdateRequest_Title {
            get {
                return ResourceManager.GetString("frmSettingsCode_UpdateRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string gbCustomize_Settings {
            get {
                return ResourceManager.GetString("gbCustomize_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string gbEdit_Main {
            get {
                return ResourceManager.GetString("gbEdit_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string gbExtra_Main {
            get {
                return ResourceManager.GetString("gbExtra_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        internal static string gbLoginInfo {
            get {
                return ResourceManager.GetString("gbLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string gbSearch_Main {
            get {
                return ResourceManager.GetString("gbSearch_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string gbTheme_Settings {
            get {
                return ResourceManager.GetString("gbTheme_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string gbTools_Main {
            get {
                return ResourceManager.GetString("gbTools_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Bank © Copyright 2020
        ///All Right Reserved. ®
        ///Made by Engin Can Yenigün.
        /// </summary>
        internal static string label1_About {
            get {
                return ResourceManager.GetString("label1_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        internal static string label1_Main {
            get {
                return ResourceManager.GetString("label1_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        internal static string label1_Recycle {
            get {
                return ResourceManager.GetString("label1_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        internal static string label1_Settings {
            get {
                return ResourceManager.GetString("label1_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First login! Please create a password and register..
        /// </summary>
        internal static string label1_ucLoginLog {
            get {
                return ResourceManager.GetString("label1_ucLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back! Please log in..
        /// </summary>
        internal static string label1_ucLoginSign {
            get {
                return ResourceManager.GetString("label1_ucLoginSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a new password and log in..
        /// </summary>
        internal static string label1_ucLoginSign_NewPass {
            get {
                return ResourceManager.GetString("label1_ucLoginSign_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        internal static string label2_Main {
            get {
                return ResourceManager.GetString("label2_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        internal static string label2_Recycle {
            get {
                return ResourceManager.GetString("label2_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string label2_Settings {
            get {
                return ResourceManager.GetString("label2_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        internal static string label2_ucLoginLog {
            get {
                return ResourceManager.GetString("label2_ucLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string label3_Main {
            get {
                return ResourceManager.GetString("label3_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string label3_Recycle {
            get {
                return ResourceManager.GetString("label3_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme:.
        /// </summary>
        internal static string label3_Settings {
            get {
                return ResourceManager.GetString("label3_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass:.
        /// </summary>
        internal static string label3_ucLoginLog {
            get {
                return ResourceManager.GetString("label3_ucLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass:.
        /// </summary>
        internal static string label3_ucLoginSign {
            get {
                return ResourceManager.GetString("label3_ucLoginSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string label4_Main {
            get {
                return ResourceManager.GetString("label4_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string label4_Recycle {
            get {
                return ResourceManager.GetString("label4_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string label4_Settings {
            get {
                return ResourceManager.GetString("label4_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Description:.
        /// </summary>
        internal static string label5_Main {
            get {
                return ResourceManager.GetString("label5_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of data: {0}.
        /// </summary>
        internal static string lblCount_Main {
            get {
                return ResourceManager.GetString("lblCount_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        internal static string lblLogo_About {
            get {
                return ResourceManager.GetString("lblLogo_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD BANK.
        /// </summary>
        internal static string lblLogo_Login {
            get {
                return ResourceManager.GetString("lblLogo_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD BANK.
        /// </summary>
        internal static string lblLogo_Main {
            get {
                return ResourceManager.GetString("lblLogo_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECYCLE BIN.
        /// </summary>
        internal static string lblLogo_Recycle {
            get {
                return ResourceManager.GetString("lblLogo_Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string lblLogo_Settings {
            get {
                return ResourceManager.GetString("lblLogo_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget your password?.
        /// </summary>
        internal static string lnkForgetPass_ucLoginSign {
            get {
                return ResourceManager.GetString("lnkForgetPass_ucLoginSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string rbDarkMode_Settings {
            get {
                return ResourceManager.GetString("rbDarkMode_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        internal static string rbLightMode_Settings {
            get {
                return ResourceManager.GetString("rbLightMode_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address and password!.
        /// </summary>
        internal static string ucLoginLogCode_InvalidInfo_Main {
            get {
                return ResourceManager.GetString("ucLoginLogCode_InvalidInfo_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID INFORMATION.
        /// </summary>
        internal static string ucLoginLogCode_InvalidInfo_Title {
            get {
                return ResourceManager.GetString("ucLoginLogCode_InvalidInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the information you entered?
        ///
        ///E-Mail: {0}
        ///Password: {1}.
        /// </summary>
        internal static string ucLoginLogCode_Register_Main {
            get {
                return ResourceManager.GetString("ucLoginLogCode_Register_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string ucLoginLogCode_Register_Title {
            get {
                return ResourceManager.GetString("ucLoginLogCode_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGET.
        /// </summary>
        internal static string ucLoginSign_MailBody1 {
            get {
                return ResourceManager.GetString("ucLoginSign_MailBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR PASSWORD?.
        /// </summary>
        internal static string ucLoginSign_MailBody2 {
            get {
                return ResourceManager.GetString("ucLoginSign_MailBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, your password reset code:.
        /// </summary>
        internal static string ucLoginSign_MailBody3 {
            get {
                return ResourceManager.GetString("ucLoginSign_MailBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Bank - PASSWORD RECOVERY CODE.
        /// </summary>
        internal static string ucLoginSign_MailSubject {
            get {
                return ResourceManager.GetString("ucLoginSign_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending the code! ERROR CODE: ERR_UCLGNSGN_MAIL.
        /// </summary>
        internal static string ucLoginSignCode_ErrorMail_Main {
            get {
                return ResourceManager.GetString("ucLoginSignCode_ErrorMail_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ucLoginSignCode_ErrorMail_Title {
            get {
                return ResourceManager.GetString("ucLoginSignCode_ErrorMail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code! Please enter valid code..
        /// </summary>
        internal static string ucLoginSignCode_InvalidCode_Main {
            get {
                return ResourceManager.GetString("ucLoginSignCode_InvalidCode_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID CODE.
        /// </summary>
        internal static string ucLoginSignCode_InvalidCode_Title {
            get {
                return ResourceManager.GetString("ucLoginSignCode_InvalidCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid new password! Please enter a valid password..
        /// </summary>
        internal static string ucLoginSignCode_InvalidNewPass_Main {
            get {
                return ResourceManager.GetString("ucLoginSignCode_InvalidNewPass_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID NEW PASSWORD.
        /// </summary>
        internal static string ucLoginSignCode_InvalidNewPass_Title {
            get {
                return ResourceManager.GetString("ucLoginSignCode_InvalidNewPass_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code sent to your e-mail address..
        /// </summary>
        internal static string ucLoginSignCode_label1_SendCode {
            get {
                return ResourceManager.GetString("ucLoginSignCode_label1_SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        internal static string ucLoginSignCode_label3_Code {
            get {
                return ResourceManager.GetString("ucLoginSignCode_label3_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget your password? - {0}.
        /// </summary>
        internal static string ucLoginSignCode_lnkForgetPassSecond {
            get {
                return ResourceManager.GetString("ucLoginSignCode_lnkForgetPassSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click Yes button, a password renewal code will be sent to your e-mail address. Are you sure?.
        /// </summary>
        internal static string ucLoginSignCode_SendCode_Main {
            get {
                return ResourceManager.GetString("ucLoginSignCode_SendCode_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD RENEW.
        /// </summary>
        internal static string ucLoginSignCode_SendCode_Title {
            get {
                return ResourceManager.GetString("ucLoginSignCode_SendCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You set new password: {0}
        ///Are you sure?.
        /// </summary>
        internal static string ucLoginSignCode_SetNewPassword_Main {
            get {
                return ResourceManager.GetString("ucLoginSignCode_SetNewPassword_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENEW PASSWORD.
        /// </summary>
        internal static string ucLoginSignCode_SetNewPassword_Title {
            get {
                return ResourceManager.GetString("ucLoginSignCode_SetNewPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password! Please enter the correct password..
        /// </summary>
        internal static string ucLoginSignCode_WrongPass_Main {
            get {
                return ResourceManager.GetString("ucLoginSignCode_WrongPass_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRONG PASSWORD.
        /// </summary>
        internal static string ucLoginSignCode_WrongPass_Title {
            get {
                return ResourceManager.GetString("ucLoginSignCode_WrongPass_Title", resourceCulture);
            }
        }
    }
}
